// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XHLrdt4WS_PT7Jh2wP6-avNxNGc184Q',
    appId: '1:392801079297:web:76d83f53e5f6f8f2f1f000',
    messagingSenderId: '392801079297',
    projectId: 'adotai-app-84d81',
    authDomain: 'adotai-app-84d81.firebaseapp.com',
    storageBucket: 'adotai-app-84d81.firebasestorage.app',
    measurementId: 'G-8Q5CJHD7F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcYOuU1ZIZo6cL3z_BaiEofsSq2CQ7beo',
    appId: '1:392801079297:android:4b198a45ff163a43f1f000',
    messagingSenderId: '392801079297',
    projectId: 'adotai-app-84d81',
    storageBucket: 'adotai-app-84d81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6Gp4eP1_3qkgjcEFk1gM1u7CuA2q_ys',
    appId: '1:392801079297:ios:36f4e5def44beb7cf1f000',
    messagingSenderId: '392801079297',
    projectId: 'adotai-app-84d81',
    storageBucket: 'adotai-app-84d81.firebasestorage.app',
    iosBundleId: 'com.example.adotaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf6Gp4eP1_3qkgjcEFk1gM1u7CuA2q_ys',
    appId: '1:392801079297:ios:36f4e5def44beb7cf1f000',
    messagingSenderId: '392801079297',
    projectId: 'adotai-app-84d81',
    storageBucket: 'adotai-app-84d81.firebasestorage.app',
    iosBundleId: 'com.example.adotaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XHLrdt4WS_PT7Jh2wP6-avNxNGc184Q',
    appId: '1:392801079297:web:12e66a4fca0c06a3f1f000',
    messagingSenderId: '392801079297',
    projectId: 'adotai-app-84d81',
    authDomain: 'adotai-app-84d81.firebaseapp.com',
    storageBucket: 'adotai-app-84d81.firebasestorage.app',
    measurementId: 'G-RSDC40LYJY',
  );
}
